// Converts MediaPipe's canonical_face_model.obj (cm) into a TypeScript data module
// (mm) consumed by the fitting core. Run after `npm run setup:models`.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const objPath = join(root, 'public', 'models', 'canonical_face_model.obj');
const outPath = join(root, 'src', 'core', 'fitting', 'canonical.ts');

const verts = [];
const uvs = [];
const tris = [];
for (const line of readFileSync(objPath, 'utf8').split('\n')) {
  const parts = line.trim().split(/\s+/);
  if (parts[0] === 'v') verts.push(parts.slice(1, 4).map((s) => Number(s) * 10)); // cm -> mm
  else if (parts[0] === 'vt') uvs.push(parts.slice(1, 3).map(Number));
  else if (parts[0] === 'f') tris.push(parts.slice(1, 4).map((s) => Number(s.split('/')[0]) - 1));
}
if (verts.length !== 468) throw new Error(`expected 468 vertices, got ${verts.length}`);
const fmt = (n) => Number(n.toFixed(4)).toString();
const src = `// GENERATED by scripts/canonical-to-ts.mjs from MediaPipe canonical_face_model.obj — do not edit.
// Units: millimetres. +Y up, +Z toward the camera (nose tip has the largest z). Origin ≈ head centre.
// Source: https://github.com/google-ai-edge/mediapipe/blob/master/mediapipe/modules/face_geometry/data/canonical_face_model.obj (Apache-2.0)

/** 468 × 3 canonical face vertices in mm. */
export const CANONICAL_VERTICES_MM = new Float32Array([
${verts.map((v) => '  ' + v.map(fmt).join(', ') + ',').join('\n')}
]);

/** 468 × 2 texture coordinates of the canonical model. */
export const CANONICAL_UVS = new Float32Array([
${uvs.map((v) => '  ' + v.map(fmt).join(', ') + ',').join('\n')}
]);

/** ${tris.length} triangles (vertex indices) tessellating the face surface. */
export const CANONICAL_TRIANGLES = new Uint16Array([
${tris.map((t) => '  ' + t.join(', ') + ',').join('\n')}
]);

export const CANONICAL_VERTEX_COUNT = 468;
`;
writeFileSync(outPath, src);
console.log(`[canonical-to-ts] wrote ${outPath}: ${verts.length} vertices, ${tris.length} triangles`);
